### PR TITLE
Append file path and line numbers to warnings

### LINKED ISSUE #12: Provide more context for "No translation for" in development mode
Maybe there should be a flag or so to show a stack trace for these cases as they can be a little tricky to debug otherwise.

### PR DESCRIPTION
**Pull request by lukejacksonn**
Fixes #12 

Warnings about missing or duplicate translations will now come with some stack trace info (thanks @JoviDeCroock!):

image

Clicking on the file path in dev tools will _jump to_ the line in the file in the sources panel. Hopefully this makes tracking down mistakes a bit easier! I didn't really feel throwing was absolutely necessary here but I can see how that strictness might be reassuring in certain situations so it is now possible to opt into a _strict_ mode that will error instead of warn:

image

This is possible by using a themed instance, with strict set to true:

```js
themed({ strict: true })
```

Not sure if it will work everywhere 🤷‍♂️ if anyone has any better ideas then I'm all ears. 

cc @bebraw

### CODE REVIEW

**Comment by bebraw** [comment]
This looks great. It would be awesome if you could make it optionally(?) to fail the entire build as a missing name implies a bug you should fix before deploying.

**Comment by lukejacksonn** [comment]
Yeh I can see value in that.. where would you expect such flags to live; in the theme?

**Comment by bebraw** [comment]
@lukejacksonn Yeah, theme feels like the perfect spot for customization.

**Comment by lukejacksonn** [comment]
Ok @bebraw it is now possible to so `themed({ strict: true })` which will cause oceanwind to throw rather than warn about missing or duplicate translations.

**Comment by bebraw** [comment]
Great. 👍

**Pull request merged**
